### ISSUE TITLE
Doesn't seem to be identifying currency signs

### ISSUE THREAD

**Issue by alexjj** [simon-v/bean-add#1]
Running this for the first time on my beancount ledger:

```
bean-add money.beancount 
553 record(s) processed
123 account(s), 679 unique description(s), 0 currency sign(s), 3 tag(s) loaded
Traceback (most recent call last):
  File "/usr/bin/bean-add", line 145, in <module>
    data.cur = data.currencies[0]
IndexError: list index out of range
```

My transactions all follow (the regular?) this structure:

```
2016/02/14 * "Chevron"
    Expenses:Car:Fuel                                    33.22 USD
    Liabilities:Chevron:Gas
```

I am using multiple currencies e.g.
```
2016/02/13 * "Dad"
    Assets:HSBC:Current                               50.00 GBP
    Income:Gift
```

I just cloned the repo right now.

**Comment by simon-v** [comment]
Thank you for your interest in my humble hack.

The issue is that bean-add expects a single whitespace or tab in certain parts of a record; in this case, between the account name and the amount.

I can compress the whitespaces when parsing and make the parts recognizable, but consequently added records will use the default, (potentially, less aesthetically pleasing) notation, not your own. Is this acceptable?

**Comment by alexjj** [comment]
Thank you for putting it together. I really like beancount and have switched to it over ledger but miss the add transaction function in ledger. 

I think what you're proposing sounds good. I have an org mode beancount file that's organized by accounts and I use the beancount minor mode and that offers an align prices function. 

I'm presuming this script adds the transaction to the end? I'm expecting to cut and paste it in other sections of my file so adjusting the gap between name and price is just another key chord. 

Thank you for this script.

**Comment by simon-v** [comment]
The script adds the transaction in an appropriate place sorted by date. Unfortunately, other assumptions then come into play:

1. That the file is sorted by date;
2. That the dates are in ISO format.

Your file will confuse bean-add, resulting in difficult-to-predict results.

Depending on your workflow and the changes you are willing to accept to it, possible solutions may include:

* Recognizing and replicating date delimiters other than "-";
* An option to output new transactions into a file other than the source file.

In the end, it may turn out, regrettably, that bean-add is simply not fit for your purposes, and i should have mentioned all those caveats in the README.

**Comment by simon-v** [comment]
Upon careful consideration, i've decided to make a few changes to how bean-add works to make it useful in a wider range of conditions; If nothing unexpected happens, i should be finished within a week. Please stay tuned.
